export const FETCH_CART_LOADING = 'FETCH_CART_LOADING';
export const FETCH_CART_DATA = 'FETCH_CART_DATA';
export const FETCH_CART_FAILED = 'ETCH_CART_FAILED';

export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGIN_DATA = 'USER_LOGIN_DATA';
export const USER_LGOIN_LOADING = 'USER_LGOIN_LOADING';

export const FETCH_ORDERS_DATA_FAILED = 'FETCH_ORDERS_DATA_FAILED';
export const FETCH_ORDERS_DATA = 'FETCH_ORDERS_DATA';
export const FETCH_ORDERS_DATA_LOADING = 'FETCH_ORDERS_DATA_LOADING';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const FETCH_USERS_DATA_FAILED = 'FETCH_USERS_DATA_FAILED';
export const FETCH_USERS_DATA = 'FETCH_USERS_DATA';
export const FETCH_USERS_DATA_LOADING = 'FETCH_USERS_DATA_LOADING';

export const CONTACT_FAILED = 'CONTACT_FAILED';
export const ADD_CONTACT_DATA = 'ADD_CONTACT_DATA';
export const CONTACT_LOADING = 'CONTACT_LOADING';

